spring:
    application:
        name: admin-inputs
    jpa:
        show-sql: true
        # hibernate:
        #     ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/TrainCompany
        username: root
        password: '12345678'
        driver-class-name: com.mysql.cj.jdbc.Driver
    graphql:
        graphiql:
            enabled: true 
